# Generated by Django 5.1.6 on 2025-02-11 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklife', '0002_worktimeperiod_delete_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Time')),
                ('record_type', models.CharField(choices=[('0', 'Start of working day'), ('1', 'End of working day'), ('2', 'Break')], max_length=1)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklife.worktimeperiod')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
