# Generated by Django 5.1.6 on 2025-02-11 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklife', '0003_worktimerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('0', 'Vacations'), ('2', 'Delay'), ('3', 'Unjustified absences'), ('3', 'Justified absences'), ('4', 'Justified absences'), ('5', 'Maternity leave'), ('6', 'Work Incapacity')], max_length=1)),
                ('comments', models.CharField(max_length=200)),
                ('incident_start', models.DateTimeField(verbose_name='IncidentStartTime')),
                ('incident_end', models.DateTimeField(verbose_name='IncidentEndTime')),
                ('applied', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
