# Generated by Django 5.1.6 on 2025-02-11 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklife', '0004_workincident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_start', models.DateTimeField(verbose_name='VacationStartTime')),
                ('vacation_end', models.DateTimeField(verbose_name='VacationEndTime')),
                ('approved', models.BooleanField(default=False)),
                ('detail', models.CharField(max_length=200)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklife.workincident')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
